const fs = require('fs'), path = require('path');
const dir = 'src/data/concepts';

function flow(steps) { return { steps }; }
function s(label, sub, annotation) { return { label, sub, annotation }; }

const configs = {
  'acid-properties': flow([
    s('Begin Txn', 'START', 'Transaction starts — DB records a begin marker in the WAL.'),
    s('Execute', 'SQL ops', 'Multiple reads/writes run. Changes held in memory — not yet committed.'),
    s('Validate', 'Integrity checks', 'DB checks constraints, foreign keys, and isolation rules.'),
    s('Commit', 'COMMIT', 'Changes durably written to disk (Durability). Visible atomically (Atomicity).'),
    s('Rollback', 'on error', 'Any failure reverts ALL changes — database returns to prior state (Atomicity).'),
  ]),
  'async-await-internals': flow([
    s('async fn', 'Returns Promise', 'async function implicitly returns a Promise wrapping the return value.'),
    s('await expr', 'Suspend fn', 'await suspends the async function — execution returns to the caller.'),
    s('Microtask Q', 'Promise resolves', 'When awaited Promise settles, continuation enqueued as a microtask.'),
    s('Resume', 'Fn continues', 'Microtask queue drains — async function resumes from where it suspended.'),
    s('Return', 'Resolve outer', 'Function returns, outer Promise resolves with the return value.'),
  ]),
  'async-await-js': flow([
    s('Call async fn', 'Invoked', 'Calling an async function starts execution synchronously until first await.'),
    s('await fetch()', 'Suspend', 'Execution suspends — event loop is freed for other tasks.'),
    s('Network I/O', 'Web API', 'Browser handles the network request in background thread.'),
    s('Response ready', 'Promise resolves', 'Response arrives — continuation queued as microtask.'),
    s('Resume', 'data = res.json()', 'Async function resumes, parses response, continues normally.'),
  ]),
  'bdd-basics': flow([
    s('Feature File', 'Gherkin syntax', 'Stakeholder writes Given/When/Then scenarios in plain English.'),
    s('Step Defs', 'Code binding', 'Developer writes step definitions that match Gherkin phrases.'),
    s('Run', 'Cucumber/Jest', 'Test runner matches scenario steps to definitions and executes them.'),
    s('Red', 'Fails first', 'Scenario fails — no implementation yet. Drives development.'),
    s('Implement', 'Write code', 'Write code to satisfy the scenario. Run again.'),
    s('Green', 'Passes', 'All scenarios green — feature is done and documented as tests.'),
  ]),
  'branch-strategies': flow([
    s('Main', 'Protected branch', 'Main/master is always deployable. Direct commits blocked.'),
    s('Feature Branch', 'git checkout -b', 'Developer creates short-lived feature branch from main.'),
    s('Commits', 'Local work', 'Iterative commits on feature branch — isolated from others.'),
    s('Pull Request', 'Code review', 'PR opened — CI runs, team reviews, discussions happen.'),
    s('Merge', 'Squash / merge', 'Approved PR merged to main. Feature branch deleted.'),
  ]),
  'caching-strategies-frontend': flow([
    s('Request', 'Browser fetch', 'Browser makes request for a resource.'),
    s('Cache Check', 'Cache-Control', 'Browser checks cache: is there a fresh stored response?'),
    s('Cache Hit', 'Serve local', 'Fresh cached response served immediately — no network.'),
    s('Revalidate', 'ETag / 304', 'Stale resource: conditional request sent. 304 Not Modified = serve cache.'),
    s('Cache Miss', 'Fetch + store', 'No cache: full network request. Response stored for future use.'),
  ]),
  'cap-theorem': flow([
    s('Write', 'Node A', 'Client writes value to Node A.'),
    s('Replicate', 'A → B', 'Node A tries to replicate to Node B.'),
    s('Partition!', 'Network split', 'Network partition — A and B cannot communicate.'),
    s('CP choice', 'Reject write', 'Consistent system rejects the write until partition heals (C + P).'),
    s('AP choice', 'Accept stale', 'Available system accepts reads on B returning stale data (A + P).'),
  ]),
  'chaos-engineering': flow([
    s('Baseline', 'Steady state', 'Measure normal system behaviour — define steady-state hypothesis.'),
    s('Hypothesis', 'What survives?', 'State what should remain true when failures are introduced.'),
    s('Inject Fault', 'Kill instance', 'Inject failure: kill a pod, add latency, cut a network link.'),
    s('Observe', 'Metrics/logs', 'Watch metrics — does the system degrade gracefully?'),
    s('Learn', 'Fix weak point', 'Hypothesis validated or broken. Fix found weakness, re-run.'),
  ]),
  'cherry-pick': flow([
    s('Find Commit', 'git log', 'Identify the commit hash to cherry-pick from another branch.'),
    s('Switch Branch', 'git checkout', 'Switch to the target branch that needs the change.'),
    s('Cherry-pick', 'git cherry-pick <hash>', 'Apply only that commit\'s diff onto the current branch.'),
    s('Conflicts?', 'Resolve if any', 'Resolve any merge conflicts introduced by the isolated patch.'),
    s('New Commit', 'Different SHA', 'New commit created with same changes but different parent — new SHA.'),
  ]),
  'closures-js': flow([
    s('Define fn', 'Outer scope', 'Outer function defines variables in its local scope.'),
    s('Inner fn', 'Captures env', 'Inner function defined — it captures a reference to outer scope variables.'),
    s('Return fn', 'Scope lives on', 'Outer function returns the inner function. Outer scope NOT garbage collected.'),
    s('Call later', 'fn() invoked', 'Inner function called later — still has access to outer variables.'),
    s('Mutation', 'Shared state', 'Mutations to captured variables are visible across all closures sharing that scope.'),
  ]),
  'concurrent-mode': flow([
    s('Work Units', 'Fiber tree', 'React breaks render work into small fiber units that can be interrupted.'),
    s('Start Render', 'beginWork', 'React starts rendering — interruptible, runs during idle time.'),
    s('Interrupt', 'Higher priority', 'Urgent update (user input) interrupts current render.'),
    s('Process Urgent', 'Sync lane', 'Urgent work completes first — user sees immediate response.'),
    s('Resume', 'Continue fiber', 'React resumes the interrupted low-priority render from where it paused.'),
    s('Commit', 'Flush to DOM', 'Commit phase: all DOM changes applied atomically — never half-rendered.'),
  ]),
  'connection-pooling': flow([
    s('App Start', 'Pool created', 'Pool initialised with min connections pre-opened to DB.'),
    s('Request', 'Acquire conn', 'Request asks pool for a connection — acquired in O(1).'),
    s('Query', 'Execute SQL', 'Connection used to execute the query against the DB.'),
    s('Release', 'Return to pool', 'Connection returned to pool — not closed, ready for next request.'),
    s('Pool Full', 'Wait / timeout', 'If all connections busy, request queues until one is released.'),
  ]),
  'container-queries': flow([
    s('Container', 'Set @container', 'Parent element declared as a containment context.'),
    s('Child Renders', 'Measures parent', 'Browser measures the container\'s inline size.'),
    s('@container rule', 'Width check', '@container (min-width: 400px) rule evaluated.'),
    s('Apply Styles', 'Conditional CSS', 'Styles applied based on container size — not viewport.'),
    s('Resize', 'Re-evaluate', 'Container resizes (e.g. sidebar collapses) — styles re-evaluated automatically.'),
  ]),
  'context-api': flow([
    s('Create Context', 'React.createContext()', 'Context object created with default value.'),
    s('Provider', '<Provider value={}>', 'Provider wraps subtree and supplies the current value.'),
    s('Consumer', 'useContext(Ctx)', 'Any descendant reads value via useContext — no prop drilling.'),
    s('Update', 'setValue()', 'Provider value changes — all consumers re-render.'),
    s('Optimise', 'Memo + split', 'Split contexts by update frequency to prevent unnecessary re-renders.'),
  ]),
  'contract-testing': flow([
    s('Consumer', 'Define contract', 'Consumer writes contract: "I expect endpoint X to return shape Y".'),
    s('Pact file', 'Publish', 'Contract (pact file) published to Pact Broker.'),
    s('Provider', 'Verify contract', 'Provider CI downloads and runs verification against the contract.'),
    s('Pass / Fail', 'CI gate', 'Provider fails CI if it can\'t satisfy the consumer contract.'),
    s('Deploy', 'Can-I-Deploy', 'Both sides check Pact Broker compatibility before deploying.'),
  ]),
  'core-web-vitals': flow([
    s('Navigation', 'User opens page', 'Browser starts loading — performance timeline begins.'),
    s('LCP', 'Largest paint', 'Largest Contentful Paint: time until largest image/text visible. Target < 2.5s.'),
    s('FID / INP', 'First input', 'Interaction to Next Paint: latency of first user interaction. Target < 200ms.'),
    s('CLS', 'Layout shifts', 'Cumulative Layout Shift: unexpected visual shifts. Target < 0.1.'),
    s('Score', 'Lighthouse audit', 'Vitals aggregated into performance score. Affects SEO ranking.'),
  ]),
  'critical-rendering-path': flow([
    s('HTML', 'Parse → DOM', 'Parser builds DOM tree from HTML bytes. Blocks on synchronous scripts.'),
    s('CSS', 'Parse → CSSOM', 'CSS downloaded and parsed into CSSOM. Render-blocking.'),
    s('Render Tree', 'DOM + CSSOM', 'Render tree combines visible DOM nodes with computed styles.'),
    s('Layout', 'Geometry calc', 'Browser computes position and size of every render tree node.'),
    s('Paint', 'Pixels to screen', 'Pixels drawn in layers. Compositor combines layers onto screen.'),
  ]),
  'css-animations': flow([
    s('Keyframes', '@keyframes def', 'Define animation states with @keyframes — from/to or percentage stops.'),
    s('Apply', 'animation: prop', 'animation property applied to element: name, duration, easing, fill-mode.'),
    s('Start', 'animation-delay', 'Animation begins after delay. animationstart event fires.'),
    s('Running', 'Compositor', 'Browser runs on compositor thread — no layout or paint for transform/opacity.'),
    s('End / Loop', 'fill-mode / count', 'animation-fill-mode retains final state. iteration-count loops.'),
  ]),
  'css-custom-properties': flow([
    s('Define', ':root { --color: }', 'Custom properties declared in :root (or any element) — scoped to subtree.'),
    s('Cascade', 'Inherited', 'Custom props cascade and inherit like regular properties.'),
    s('Use', 'var(--color)', 'var() reads the property — fallback value optional: var(--x, red).'),
    s('Override', 'Local scope', 'Any descendant can redefine the property — creates local scope.'),
    s('JS access', 'getPropertyValue', 'JS can read/write custom properties at runtime for dynamic theming.'),
  ]),
  'css-grid': flow([
    s('Container', 'display: grid', 'Parent becomes grid container. Children become grid items.'),
    s('Tracks', 'columns / rows', 'grid-template-columns/rows define track sizes. fr, minmax(), auto.'),
    s('Placement', 'Auto or explicit', 'Items auto-placed by grid algorithm, or placed with grid-column/row.'),
    s('Areas', 'grid-template-areas', 'Named areas create readable layouts. Items reference area by name.'),
    s('Align', 'justify/align', 'justify-items, align-items, gap control alignment and spacing.'),
  ]),
  'css-specificity-cascade': flow([
    s('Collect Rules', 'All stylesheets', 'Browser collects all CSS rules targeting an element.'),
    s('Origin', 'UA / Author / User', 'Rules ranked by origin: user-agent < author < inline.'),
    s('Specificity', 'ID > class > tag', 'Same-origin rules ranked: (ID count, class count, tag count) tuple.'),
    s('Order', 'Last wins', 'Equal specificity: later declaration wins.'),
    s('Computed Value', 'Cascade winner', 'Winning value computed — inheritable properties passed to children.'),
  ]),
  'dead-letter-queues': flow([
    s('Message', 'Published to queue', 'Producer publishes message to main queue.'),
    s('Consume', 'Process attempt', 'Consumer picks up message and attempts processing.'),
    s('Failure', 'Nack / error', 'Processing fails — message nacked or throws. Retry count incremented.'),
    s('Max Retries', 'Retry limit hit', 'After max retries, broker routes message to Dead Letter Queue.'),
    s('DLQ', 'Inspect & replay', 'Ops team inspects DLQ. Fix root cause and replay to main queue.'),
  ]),
  'environment-management': flow([
    s('Dev', '.env.local', 'Local dev uses .env.local — secrets never committed to git.'),
    s('CI', 'Injected vars', 'CI injects env vars at build time from secrets manager.'),
    s('Staging', 'Staging config', 'Staging mirrors prod config but with non-prod endpoints.'),
    s('Prod', 'Secret manager', 'Production reads from HashiCorp Vault / AWS Secrets Manager at runtime.'),
    s('Rotate', 'Zero downtime', 'Secrets rotated in manager — no code change or redeploy needed.'),
  ]),
  'esm-vs-cjs': flow([
    s('CJS require()', 'Runtime load', 'require() executes synchronously at runtime — dynamic, conditional loads OK.'),
    s('CJS exports', 'module.exports', 'Module exports assigned to module.exports — object reference, mutable.'),
    s('ESM import', 'Parse-time', 'import statements resolved at parse time — static analysis possible.'),
    s('ESM Tree-shake', 'Dead code elim', 'Bundlers eliminate unused named exports — impossible with CJS.'),
    s('Interop', 'require(esm)?', 'CJS cannot require() ESM directly. ESM can import CJS (default export only).'),
  ]),
  'event-driven-architecture': flow([
    s('Event', 'Produced', 'Producer emits event: "order.placed" with payload.'),
    s('Event Bus', 'Kafka / SNS', 'Event persisted to durable event bus / message broker.'),
    s('Subscribers', 'Fan-out', 'Multiple consumers independently subscribe to the event.'),
    s('Process', 'Each consumer', 'Each consumer processes at its own pace — fully decoupled.'),
    s('Replay', 'Event log', 'Events stored permanently — consumers can replay from any offset.'),
  ]),
  'event-sourcing': flow([
    s('Command', 'PlaceOrder', 'Command arrives — validated against current state.'),
    s('Event', 'OrderPlaced', 'If valid, an immutable domain event is appended to the event store.'),
    s('Event Store', 'Append-only', 'Events never updated or deleted — the log is the source of truth.'),
    s('Projection', 'Rebuild state', 'Current state is derived by replaying events from the log.'),
    s('Read Model', 'Query view', 'Separate read model (projection) updated by event handlers for queries.'),
  ]),
  'eventual-consistency': flow([
    s('Write', 'Primary node', 'Write committed to primary node. Immediately visible there.'),
    s('Replicate', 'Async lag', 'Change asynchronously propagated to replica nodes — lag exists.'),
    s('Stale Read', 'Replica returns old', 'Read on replica may return old value during propagation window.'),
    s('Converge', 'All nodes sync', 'Given no new writes, all nodes eventually converge to same value.'),
    s('Read-your-writes', 'Sticky session', 'Strategy: route user reads to primary or track vector clock.'),
  ]),
  'flexbox-algorithm': flow([
    s('Container', 'display: flex', 'Flex container established. Children become flex items.'),
    s('Main Axis', 'flex-direction', 'Main axis set by flex-direction: row (default) or column.'),
    s('Flexibility', 'flex-grow/shrink', 'Available space distributed: flex-grow expands, flex-shrink contracts.'),
    s('Alignment', 'justify/align', 'justify-content aligns on main axis. align-items on cross axis.'),
    s('Wrapping', 'flex-wrap', 'flex-wrap: wrap allows items to flow to new lines when needed.'),
  ]),
  'font-optimization': flow([
    s('Discover', 'CSS @font-face', 'Browser parses @font-face — font not downloaded yet (lazy).'),
    s('FOIT/FOUT', 'Text renders', 'Font loading delay causes invisible text (FOIT) or fallback swap (FOUT).'),
    s('Preload', '<link rel=preload>', 'Preloading font hints browser to fetch early — reduces FOIT.'),
    s('Subsetting', 'unicode-range', 'Only load glyphs needed for the page language — smaller file.'),
    s('font-display', 'swap strategy', 'font-display: swap shows fallback immediately, swaps when ready.'),
  ]),
  'github-actions': flow([
    s('Push / PR', 'Event trigger', 'Workflow triggered by git event: push, pull_request, schedule.'),
    s('Runner', 'ubuntu-latest', 'GitHub provisions a fresh virtual machine to run the job.'),
    s('Checkout', 'actions/checkout', 'Repository code checked out onto the runner.'),
    s('Steps', 'Run commands', 'Steps execute sequentially: install, build, test, deploy.'),
    s('Artifacts', 'Upload / cache', 'Build artifacts uploaded. Dependencies cached for next run.'),
  ]),
  'graphql-basics': flow([
    s('Query', 'Client sends', 'Client sends typed query — declares exactly what fields it needs.'),
    s('Parse', 'AST built', 'Server parses query into AST, validates against schema.'),
    s('Resolve', 'Resolver chain', 'Each field resolved by its resolver function — fetch from DB/service.'),
    s('DataLoader', 'Batch N+1', 'DataLoader batches and deduplicates sub-resolver DB calls.'),
    s('Response', 'Shape matches query', 'Response JSON exactly mirrors query structure — no over/under-fetching.'),
  ]),
  'idempotency': flow([
    s('Request', 'Idempotency-Key header', 'Client sends request with unique Idempotency-Key.'),
    s('Check', 'Key in store?', 'Server checks Redis/DB: has this key been processed before?'),
    s('Already done', 'Return cached', 'Key found: return cached response immediately — don\'t re-process.'),
    s('Process', 'Execute op', 'New key: execute the operation normally.'),
    s('Store', 'Save result', 'Store result keyed by Idempotency-Key. Retries return same response.'),
  ]),
  'image-optimization': flow([
    s('Source', 'Original PNG/JPEG', 'Large original image uploaded or referenced.'),
    s('Format', 'WebP / AVIF', 'Convert to modern format — WebP ~30% smaller, AVIF ~50% smaller.'),
    s('Responsive', 'srcset sizes', 'Multiple sizes generated. Browser picks smallest that fits display.'),
    s('Lazy Load', 'loading=lazy', 'Off-screen images deferred — only load as user scrolls near.'),
    s('CDN', 'Serve from edge', 'Optimised images served from CDN edge — low latency worldwide.'),
  ]),
  'incident-response': flow([
    s('Alert', 'PagerDuty fires', 'Alert triggered — on-call engineer paged within SLO breach window.'),
    s('Triage', 'Assess severity', 'Responder identifies scope: which services affected, how many users.'),
    s('Mitigate', 'Stop the bleeding', 'Immediate mitigation: rollback, feature flag off, traffic shift.'),
    s('Resolve', 'Root cause fix', 'Root cause identified and fixed. System returns to steady state.'),
    s('Post-mortem', 'Blameless review', 'Blameless post-mortem: timeline, contributing factors, action items.'),
  ]),
  'input-validation': flow([
    s('Input arrives', 'User / API data', 'Untrusted data arrives at the system boundary.'),
    s('Type check', 'Schema validate', 'Type, format, and length validated against schema (Zod, Joi).'),
    s('Whitelist', 'Allowed values', 'Allowlist validation preferred over blacklist — reject unknown.'),
    s('Sanitise', 'Strip HTML', 'Sanitise for output context: HTML encode, SQL parameterise.'),
    s('Reject', '400 Bad Request', 'Invalid input rejected with descriptive error — never silently dropped.'),
  ]),
  'interactive-rebase': flow([
    s('Choose range', 'git rebase -i HEAD~N', 'Open interactive rebase for last N commits.'),
    s('Editor opens', 'Pick / squash list', 'Editor shows commit list. Change "pick" to squash/edit/reword/drop.'),
    s('Squash', 'Combine commits', 'squash merges commit into previous — prompts for combined message.'),
    s('Reword', 'Edit message', 'reword pauses to let you edit the commit message.'),
    s('New history', 'Force push', 'Rewritten commits get new SHAs. Force push required for shared branches.'),
  ]),
  'job-queues': flow([
    s('Enqueue', 'Add job', 'Producer adds job to queue with payload and priority.'),
    s('Persist', 'Redis / DB', 'Job persisted durably — survives worker restart.'),
    s('Worker', 'Poll / listen', 'Worker process picks up job — moves to "active" state.'),
    s('Execute', 'Run job fn', 'Job handler runs. On error: retried with backoff up to max attempts.'),
    s('Complete', 'Remove job', 'On success: job removed from queue. Result stored if needed.'),
  ]),
  'jwt-authentication': flow([
    s('Login', 'POST /auth', 'Client sends credentials to auth endpoint.'),
    s('Validate', 'Check hash', 'Server verifies password hash against stored bcrypt hash.'),
    s('Sign JWT', 'header.payload.sig', 'Server signs JWT with secret (HS256) or private key (RS256). Payload: userId, exp.'),
    s('Return', '200 + token', 'Token returned — stored in httpOnly cookie or memory (not localStorage).'),
    s('Request', 'Authorization: Bearer', 'Client sends JWT in Authorization header on protected routes.'),
    s('Verify', 'Signature + exp', 'Server verifies signature and expiry — stateless, no DB lookup.'),
  ]),
  'keyboard-navigation': flow([
    s('Tab order', 'DOM order', 'Tab key moves focus through interactive elements in DOM order.'),
    s('Focus ring', ':focus-visible', 'Focused element shows visible focus indicator via :focus-visible.'),
    s('Trap focus', 'Modal / dialog', 'Dialog traps focus inside — Tab wraps, Escape closes.'),
    s('Arrow keys', 'Widget roles', 'Composite widgets (menu, tabs) handle arrow keys internally per ARIA pattern.'),
    s('Skip links', 'Bypass blocks', '"Skip to main" link lets keyboard users bypass repeated navigation.'),
  ]),
  'lazy-loading-frontend': flow([
    s('Page Load', 'Viewport check', 'Initial render: only load assets in the viewport.'),
    s('IntersectionObserver', 'Watch elements', 'Observer watches off-screen images and components.'),
    s('Enters viewport', 'Threshold met', 'Element scrolls into view — observer callback fires.'),
    s('Fetch', 'Load resource', 'Image src set or component chunk fetched now.'),
    s('Render', 'Content appears', 'Resource loaded and rendered — user sees content just in time.'),
  ]),
  'lazy-vs-eager-loading': flow([
    s('Eager Load', 'All upfront', 'Eager: load all data/modules at startup. Fast after — slow initial.'),
    s('Lazy Load', 'On demand', 'Lazy: load data/module only when first needed. Faster startup.'),
    s('Trade-off', 'First access latency', 'Lazy introduces latency on first access. Eager wastes resources for unused items.'),
    s('Hybrid', 'Prefetch idle', 'Best practice: lazy load + prefetch during idle time for likely-needed items.'),
  ]),
  'lighthouse-scoring': flow([
    s('Audit', 'Lighthouse runs', 'Lighthouse loads the page and collects metrics via Chrome DevTools.'),
    s('Performance', 'LCP FID CLS', 'Core Web Vitals measured — weighted into performance score (0-100).'),
    s('Accessibility', 'ARIA audit', 'Checks colour contrast, ARIA roles, focus management.'),
    s('Best Practices', 'Security / APIs', 'Checks HTTPS, deprecated APIs, console errors.'),
    s('SEO', 'Meta / crawlability', 'Checks meta descriptions, viewport, structured data.'),
  ]),
  'memory-leaks-backend': flow([
    s('Allocate', 'Object created', 'Object allocated — heap grows. Expected.'),
    s('Reference held', 'GC cannot free', 'Unintended reference kept (global, closure, listener) — GC can\'t collect.'),
    s('Heap grows', 'RSS increases', 'Heap grows with each request/operation but never shrinks. OOM eventually.'),
    s('Detect', 'Heap snapshot', 'Take heap snapshots over time — growing object counts identify leak source.'),
    s('Fix', 'Remove reference', 'Remove stale reference: clear map/set, removeEventListener, nullify variable.'),
  ]),
  'memory-management-gc': flow([
    s('Allocate', 'new Object()', 'Object allocated on heap — counted as reachable from root.'),
    s('GC roots', 'Stack + globals', 'GC starts from roots: stack variables, global references.'),
    s('Mark', 'Reachability trace', 'Mark-and-sweep traces all reachable objects from roots.'),
    s('Sweep', 'Collect unreachable', 'Unreachable objects swept — memory reclaimed.'),
    s('Compact', 'Defragment heap', 'Compaction moves live objects together — reduces fragmentation.'),
  ]),
  'merge-vs-rebase': flow([
    s('Feature branch', 'Diverged from main', 'Feature branch has commits not in main, and main has moved forward.'),
    s('Merge', 'git merge main', 'Merge: creates merge commit — preserves branch history and context.'),
    s('Merge commit', 'Non-linear history', 'History shows when branches diverged and merged — non-linear.'),
    s('Rebase', 'git rebase main', 'Rebase: replays feature commits on top of latest main — linear history.'),
    s('New SHAs', 'Rewritten commits', 'Rebased commits get new hashes. Never rebase shared branches.'),
  ]),
  'microtasks-vs-macrotasks': flow([
    s('Sync code', 'Call stack', 'Synchronous code runs on call stack first.'),
    s('Stack empty', 'Check microtasks', 'When stack empties, microtask queue checked before anything else.'),
    s('Microtasks', 'Drain all', 'ALL microtasks drain: Promise .then, queueMicrotask, MutationObserver.'),
    s('Render', 'Optional', 'Browser may render (rAF) — only if microtask queue is empty.'),
    s('Macrotask', 'One per loop', 'ONE macrotask runs: setTimeout, setInterval, I/O callback. Then repeat.'),
  ]),
  'mocking-strategies-frontend': flow([
    s('Identify dep', 'Isolate unit', 'Identify which dependency to replace — HTTP, module, or class.'),
    s('Stub', 'Return value', 'Stub returns a fixed value — simplest mock. No behaviour verification.'),
    s('Mock', 'Spy + assert', 'Mock records calls — verify it was called with correct args.'),
    s('MSW', 'Intercept fetch', 'Mock Service Worker intercepts at network level — realistic HTTP mocking.'),
    s('Teardown', 'Restore after test', 'Restore mocks after each test — prevent test pollution.'),
  ]),
  'mutation-testing': flow([
    s('Original tests', 'Test suite runs', 'Run existing test suite — all tests pass (green baseline).'),
    s('Generate mutants', 'Modify source', 'Mutation tool generates variants: flip operators, change values, remove lines.'),
    s('Run tests', 'Per mutant', 'Full test suite re-run for each mutant.'),
    s('Killed', 'Test caught it', 'Mutant killed: at least one test fails — tests are effective.'),
    s('Survived', 'Gap in coverage', 'Mutant survives: no test caught the change — write a better test.'),
  ]),
  'n-plus-one-query': flow([
    s('Load list', 'SELECT * posts', 'Query 1: fetch N post records.'),
    s('Loop', 'For each post', 'Code iterates over posts.'),
    s('N queries', 'SELECT author', 'Each iteration fires a separate query for the author — N total.'),
    s('1+N total', 'Slow page', '1 + N queries. 100 posts = 101 queries. Scales terribly.'),
    s('Fix: JOIN', 'Eager load', 'Fix with JOIN or ORM eager loading (includes) — 1 or 2 queries total.'),
  ]),
  'observability-logs-metrics-traces': flow([
    s('Request', 'Enters system', 'HTTP request hits service A.'),
    s('Logs', 'Structured events', 'Service logs structured events: level, message, context, trace-id.'),
    s('Metrics', 'Counters/histograms', 'Service increments counters, records histogram latencies (Prometheus).'),
    s('Trace', 'Span created', 'Distributed trace span created. Propagated to service B via headers.'),
    s('Correlate', 'Trace-id', 'trace-id ties logs + spans + metrics together for a single request.'),
  ]),
  'overfitting-underfitting': flow([
    s('Training', 'Model learns', 'Model trained on training set — loss decreases.'),
    s('Validate', 'Validation loss', 'Track validation loss alongside training loss.'),
    s('Underfit', 'Both losses high', 'High train + val loss: model too simple — increase capacity or train longer.'),
    s('Good fit', 'Both losses low', 'Low train + val loss, small gap: generalises well.'),
    s('Overfit', 'Val loss rises', 'Train loss low, val loss climbs: memorising data. Add dropout/regularisation.'),
  ]),
  'owasp-top-10': flow([
    s('Input', 'Untrusted data', 'All external input is untrusted: headers, body, cookies, query strings.'),
    s('Injection', 'Parameterise', 'A03 Injection: use parameterised queries, never string-concatenate SQL.'),
    s('Auth', 'Strong sessions', 'A07 Auth failures: bcrypt passwords, httpOnly cookies, MFA.'),
    s('XSS', 'Encode output', 'A03 XSS: HTML-encode output, CSP headers, avoid innerHTML.'),
    s('Logging', 'Monitor anomalies', 'A09 Logging failures: log all auth events, alert on anomalies.'),
  ]),
  'password-hashing': flow([
    s('Registration', 'Plain password', 'User submits plain-text password over HTTPS.'),
    s('Salt', 'Random bytes', 'Generate random salt (16+ bytes) — unique per user.'),
    s('Hash', 'bcrypt / argon2', 'Hash = bcrypt(password + salt, cost=12). Intentionally slow.'),
    s('Store', 'Hash only', 'Store only the hash+salt — never the plain password. Ever.'),
    s('Login', 'Recompute hash', 'On login: recompute hash and compare with stored — timing-safe compare.'),
  ]),
  'prefetching-preloading': flow([
    s('Analyse', 'Critical resources', 'Identify render-critical resources: fonts, hero image, key scripts.'),
    s('Preload', '<link rel=preload>', 'Preload: fetch high-priority resource early — same page, critical path.'),
    s('Prefetch', '<link rel=prefetch>', 'Prefetch: fetch likely-needed next-page resource during idle time.'),
    s('DNS prefetch', 'Resolve early', 'dns-prefetch resolves third-party hostnames before they\'re needed.'),
    s('Preconnect', 'TCP + TLS early', 'preconnect opens TCP + TLS to origin before the request is made.'),
  ]),
  'profiling-benchmarking': flow([
    s('Baseline', 'Measure first', 'Establish baseline metrics before optimising — never guess.'),
    s('Profile', 'CPU / heap', 'CPU profiler shows hot functions. Heap snapshot shows allocations.'),
    s('Identify', 'Hot path', 'Find the bottleneck: 80% of time in 20% of code.'),
    s('Optimise', 'Targeted fix', 'Optimise only the hot path. Premature optimisation wastes time.'),
    s('Verify', 'Re-benchmark', 'Re-run benchmark to confirm improvement. Compare before/after numbers.'),
  ]),
  'property-based-testing': flow([
    s('Define', 'Property spec', 'Define a property that must hold for ALL inputs: e.g. sort(x).length === x.length.'),
    s('Generate', 'Random inputs', 'Framework generates hundreds of random inputs satisfying type constraints.'),
    s('Run', 'Test each input', 'Property tested against every generated input.'),
    s('Shrink', 'Minimal failing case', 'On failure, framework shrinks input to minimal failing example.'),
    s('Fix', 'Edge case found', 'Edge case surfaced. Fix the implementation. Add the case to regression suite.'),
  ]),
  'pubsub-pattern': flow([
    s('Publisher', 'Emit event', 'Publisher emits event to the event bus — no knowledge of subscribers.'),
    s('Event Bus', 'Route by topic', 'Bus routes message to all subscribers of that topic.'),
    s('Subscriber A', 'Handle event', 'Subscriber A processes independently.'),
    s('Subscriber B', 'Handle event', 'Subscriber B processes independently — fully decoupled.'),
    s('Decouple', 'Add/remove freely', 'New subscribers added without changing publisher code.'),
  ]),
  'query-optimization': flow([
    s('Slow query', 'EXPLAIN ANALYZE', 'Run EXPLAIN ANALYZE to see the query plan and actual times.'),
    s('Seq scan', 'No index', 'Sequential scan: reading every row. Bad for large tables with filters.'),
    s('Add index', 'B-tree on col', 'Add index on filter/sort column. Planner switches to index scan.'),
    s('Covering index', 'Include columns', 'Include projected columns in index — query satisfied without heap fetch.'),
    s('Verify', 'Re-EXPLAIN', 'Re-run EXPLAIN ANALYZE — confirm index used and rows examined reduced.'),
  ]),
  'react-fiber': flow([
    s('Update', 'setState called', 'State change triggers a re-render request.'),
    s('Work loop', 'Fiber units', 'Fiber reconciler breaks work into units — each fiber = one component.'),
    s('Render phase', 'Interruptible', 'Render phase: pure computation, can be interrupted by higher-priority work.'),
    s('Lanes', 'Priority queue', 'Updates assigned to lanes: sync, transition, background. Urgent lanes run first.'),
    s('Commit', 'Uninterruptible', 'Commit phase: DOM mutations applied atomically — never interrupted.'),
  ]),
  'react-server-components': flow([
    s('Request', 'Server receives', 'Client navigates — server receives request.'),
    s('RSC render', 'On server', 'Server Components render on the server: DB queries, no JS bundle shipped.'),
    s('Serialise', 'RSC wire format', 'React serialises component tree (not HTML) to wire format.'),
    s('Client', 'Merge tree', 'Client merges server tree with interactive Client Components.'),
    s('No hydration', 'For SC', 'Server Components never hydrate — zero client-side JS for static parts.'),
  ]),
  'react-testing-library': flow([
    s('Render', 'render(<Component>)', 'Component rendered into jsdom — realistic DOM environment.'),
    s('Query', 'getByRole / Text', 'Query by accessibility role, label, or text — as a user would find it.'),
    s('Interact', 'userEvent.click', 'Simulate user interactions: click, type, keyboard.'),
    s('Assert', 'expect().toBeInDoc', 'Assert on DOM state — visible text, ARIA state, form values.'),
    s('Clean up', 'afterEach', 'DOM and state cleaned up automatically after each test.'),
  ]),
  'refactoring-patterns': flow([
    s('Identify', 'Code smell', 'Identify a code smell: duplication, long method, magic numbers.'),
    s('Test first', 'Green baseline', 'Ensure tests pass before touching code — safety net.'),
    s('Small step', 'One change', 'Apply one refactoring at a time: extract method, rename, inline.'),
    s('Run tests', 'Still green?', 'Tests must stay green after every step — refactoring not behaviour change.'),
    s('Repeat', 'Clean design', 'Iterate until design is clean. Commit after each safe step.'),
  ]),
  'reflow-vs-repaint': flow([
    s('DOM change', 'Style / layout', 'JavaScript changes element style or DOM structure.'),
    s('Recalc styles', 'Cascade', 'Browser recalculates computed styles for affected elements.'),
    s('Reflow', 'Layout pass', 'Reflow: geometry recalculated — position, size. Expensive, propagates up.'),
    s('Repaint', 'Pixels drawn', 'Repaint: visual update without layout change (color, shadow). Cheaper.'),
    s('Composite', 'GPU layer', 'transform/opacity changes skip reflow+repaint — handled by compositor.'),
  ]),
  'render-pipeline': flow([
    s('Parse', 'HTML + CSS', 'Browser parses HTML → DOM. CSS → CSSOM.'),
    s('Render tree', 'Merge', 'DOM + CSSOM merged into render tree (only visible nodes).'),
    s('Layout', 'Geometry', 'Layout (reflow): compute exact position and size of each box.'),
    s('Paint', 'Draw calls', 'Paint: generate draw calls per layer (background, border, text).'),
    s('Composite', 'GPU assembly', 'Compositor assembles layers on GPU and displays frame.'),
  ]),
  'repository-pattern': flow([
    s('Service', 'Calls repo', 'Business logic calls repository interface: repo.findById(id).'),
    s('Repo interface', 'Abstraction', 'Repository interface hides data access details from the service.'),
    s('Concrete repo', 'DB queries', 'Concrete implementation translates calls to SQL/ORM queries.'),
    s('Return domain', 'Domain objects', 'Raw DB rows mapped to domain entities before returning.'),
    s('Test swap', 'In-memory repo', 'Tests inject in-memory repository — no real DB needed.'),
  ]),
  'request-animation-frame': flow([
    s('Schedule', 'rAF(callback)', 'requestAnimationFrame schedules callback before next browser paint.'),
    s('Vsync', '60fps budget', 'Browser waits for vsync — typically 16.67ms frame budget.'),
    s('Callback fires', 'Before paint', 'rAF callback runs — reads layout, applies DOM changes.'),
    s('Paint', 'Frame rendered', 'Browser paints the frame. Smooth animation at display refresh rate.'),
    s('Next frame', 'Call rAF again', 'For continuous animation, call rAF again inside the callback.'),
  ]),
  'responsive-design': flow([
    s('Viewport', 'meta viewport', 'Set <meta name="viewport"> — tells mobile to use device width.'),
    s('Fluid layout', 'Relative units', 'Use %, rem, vw instead of fixed px — layout scales naturally.'),
    s('Breakpoints', '@media queries', 'Media queries apply styles at specific viewport width thresholds.'),
    s('Images', 'srcset sizes', 'Responsive images: provide multiple sizes, browser picks optimal.'),
    s('Test', 'DevTools emulation', 'Test at common breakpoints — mobile-first approach recommended.'),
  ]),
  'rest-api-design': flow([
    s('Resources', 'Noun URIs', 'URIs identify resources (nouns): /users/:id, /posts/:id/comments.'),
    s('HTTP verbs', 'GET POST PUT DELETE', 'HTTP methods express intent: GET=read, POST=create, PUT=replace, PATCH=update, DELETE=remove.'),
    s('Status codes', 'Semantic response', '200 OK, 201 Created, 400 Bad Request, 404 Not Found, 409 Conflict.'),
    s('HATEOAS', 'Links in response', 'Response includes links to related actions — client discovers API dynamically.'),
    s('Versioning', '/v1/ prefix', 'Version in URL or header — never break existing clients.'),
  ]),
  'retry-and-backoff': flow([
    s('Request', 'Attempt 1', 'Initial request sent.'),
    s('503 received', 'Transient error', 'Transient failure (503 / 429 / network timeout) — eligible for retry.'),
    s('Wait', '1s + jitter', 'Wait base_delay * 2^attempt + random_jitter before next attempt.'),
    s('Attempt 2', 'Retry', 'Retry sent. Jitter prevents thundering herd from many clients retrying together.'),
    s('Success / give up', 'Max retries', 'Success: proceed. Max retries hit: fail with error to caller.'),
  ]),
  'saga-pattern': flow([
    s('Start saga', 'Orchestrator', 'Saga orchestrator receives command: ProcessOrder.'),
    s('Step 1', 'Reserve inventory', 'Call inventory service: reserve items. Store compensation: release.'),
    s('Step 2', 'Charge payment', 'Call payment service: charge card. Store compensation: refund.'),
    s('Step 3', 'Schedule delivery', 'Call delivery service. All steps committed — saga complete.'),
    s('Rollback', 'Compensate in reverse', 'On any failure: execute compensating transactions in reverse order.'),
  ]),
  'screen-reader-compatibility': flow([
    s('DOM', 'Parsed', 'Browser builds DOM and sends to accessibility tree.'),
    s('Accessibility tree', 'AOM', 'Accessibility Object Model derived: roles, names, states, properties.'),
    s('ARIA', 'role / aria-label', 'ARIA attributes patch the accessibility tree where HTML semantics fall short.'),
    s('Screen reader', 'Announce', 'Screen reader reads accessibility tree — announces role, name, state.'),
    s('Keyboard', 'Navigate', 'User navigates with keyboard — focus management must be explicit for SPAs.'),
  ]),
  'secrets-management': flow([
    s('Dev', '.env (local only)', 'Development: .env file, never committed. gitignored.'),
    s('CI', 'Injected at build', 'CI: secrets injected as env vars from CI secret store. Not in code.'),
    s('Production', 'Secrets manager', 'Production: app fetches secrets from Vault / AWS Secrets Manager at runtime.'),
    s('Rotate', 'Zero-downtime', 'Rotation: update secret in manager. App picks up on next fetch — no redeploy.'),
    s('Audit', 'Access log', 'All secret access logged — who accessed what and when.'),
  ]),
  'semantic-versioning': flow([
    s('MAJOR', 'Breaking change', 'Bump MAJOR (1.x.x → 2.0.0) for breaking API changes.'),
    s('MINOR', 'New feature', 'Bump MINOR (x.1.x → x.2.0) for backward-compatible new features.'),
    s('PATCH', 'Bug fix', 'Bump PATCH (x.x.1 → x.x.2) for backward-compatible bug fixes.'),
    s('Pre-release', '1.0.0-beta.1', 'Pre-release tags: alpha, beta, rc — lower precedence than release.'),
    s('Range', '^1.2.3 ~1.2.3', '^ allows minor+patch updates. ~ allows only patch updates. = pins exact.'),
  ]),
  'server-sent-events': flow([
    s('Client', 'EventSource(url)', 'Client opens persistent HTTP connection via EventSource API.'),
    s('Server', 'text/event-stream', 'Server responds with Content-Type: text/event-stream. Connection held open.'),
    s('Push', 'data: payload\\n\\n', 'Server pushes data: ... events anytime. No polling needed.'),
    s('Reconnect', 'Auto-retry', 'On disconnect, EventSource automatically reconnects with Last-Event-ID.'),
    s('One-way', 'Server → Client', 'SSE is one-way: server → client only. Use WebSockets for bidirectional.'),
  ]),
  'shadow-dom': flow([
    s('Create', 'attachShadow()', 'element.attachShadow({mode:open}) creates an isolated DOM subtree.'),
    s('Shadow root', 'Boundary', 'Shadow root is a boundary — styles and DOM inside don\'t leak out, and vice versa.'),
    s('Slot', '<slot>', '<slot> elements define where Light DOM children are projected into shadow.'),
    s('Style', 'Scoped CSS', 'CSS inside shadow root only affects shadow DOM — no cascade leakage.'),
    s('::part', 'Expose styling hooks', '::part() CSS pseudo-element lets the outside style specific shadow parts.'),
  ]),
  'sla-design': flow([
    s('Define', 'SLI + SLO', 'Define SLIs (measured metrics) and SLOs (targets): 99.9% uptime.'),
    s('Error budget', 'Remaining allowance', 'Error budget = 1 - SLO. 0.1% = 43.8 min/month downtime allowed.'),
    s('Measure', 'Real traffic', 'Measure SLIs from real user traffic — synthetic monitors miss edge cases.'),
    s('Burn rate', 'Alert on rate', 'Alert when error budget burns faster than expected — incident in progress.'),
    s('Review', 'Monthly meeting', 'SLA review: adjust SLOs, prioritise reliability work if budget exhausted.'),
  ]),
  'snapshot-testing': flow([
    s('First run', 'Snapshot created', 'First test run: render component, serialize output, save to .snap file.'),
    s('Next run', 'Compare snapshot', 'Subsequent runs: render component, compare to saved snapshot.'),
    s('Match', 'Test passes', 'Output matches snapshot — component unchanged.'),
    s('Mismatch', 'Test fails', 'Output differs — intentional change or regression?'),
    s('Update', 'jest --updateSnapshot', 'Intentional change: update snapshot. Regression: fix the bug.'),
  ]),
  'source-maps': flow([
    s('Source', 'TypeScript / JSX', 'Original source written in TypeScript, JSX, or other transpiled language.'),
    s('Compile', 'Transpile + bundle', 'Build tool transpiles and bundles — output is minified JS.'),
    s('Source map', '.map file', 'Source map file generated: maps minified positions to original file:line.'),
    s('Browser', 'DevTools loads map', 'Browser DevTools loads source map — shows original source in debugger.'),
    s('Error', 'Mapped stack trace', 'Runtime error stack trace mapped to original file and line number.'),
  ]),
  'sql-injection': flow([
    s('Input', 'Malicious string', 'Attacker enters: \' OR 1=1 -- in a form field.'),
    s('Concat', 'Vulnerable code', 'Vulnerable code: "SELECT * FROM users WHERE name=\'" + input + "\'". Input terminates string and appends new SQL.'),
    s('Exploit', 'Bypass auth / dump DB', 'Injected SQL executes: returns all rows, drops tables, or exfiltrates data.'),
    s('Parameterise', 'db.query(sql, [input])', 'Fix: use parameterised queries — input treated as data, never as SQL.'),
    s('ORM', 'Escape + map', 'ORMs parameterise automatically. Never use raw string concatenation.'),
  ]),
  'stacking-context': flow([
    s('Triggers', 'position + z-index', 'Stacking context created by: position+z-index, opacity<1, transform, filter.'),
    s('Local order', 'Within context', 'z-index only competes within the same stacking context — not globally.'),
    s('Paint order', '7-step rule', 'Background → negative z → block flow → floats → inline → z=0 → positive z.'),
    s('Isolation', 'isolation: isolate', 'isolation: isolate forces a new context — prevents z-index fights with other layers.'),
    s('Debug', 'Layers panel', 'Chrome DevTools Layers panel visualises each stacking context as a layer.'),
  ]),
  'stateless-services': flow([
    s('Request', 'Any instance', 'Request arrives — routed to any available instance (no affinity needed).'),
    s('No session', 'JWT / context in req', 'All state passed in the request (JWT, params) — server stores nothing.'),
    s('Process', 'Compute + DB', 'Instance computes and reads/writes external state store (DB, cache).'),
    s('Respond', 'Return', 'Response returned. Instance forgets everything about this request.'),
    s('Scale', 'Add/remove freely', 'Instances added or removed at any time — zero state migration.'),
  ]),
  'static-analysis': flow([
    s('Source', 'Code file', 'Source file fed to static analyser.'),
    s('Parse', 'AST built', 'Code parsed into Abstract Syntax Tree without executing.'),
    s('Rules', 'Pattern match', 'Rules engine traverses AST — matches patterns (unused vars, type errors, security).'),
    s('Report', 'File:line:col', 'Violations reported with file, line, column, and severity.'),
    s('Fix', 'CI gate', 'CI blocks merge on errors. Warnings flagged for human review.'),
  ]),
  'suspense-react': flow([
    s('Render', 'Component tree', 'React renders the component tree.'),
    s('Suspend', 'Promise thrown', 'Suspending component throws a Promise (data not ready yet).'),
    s('Boundary', 'Nearest Suspense', 'React catches the thrown Promise at the nearest Suspense boundary.'),
    s('Fallback', 'Show spinner', 'Suspense renders the fallback (spinner/skeleton) while promise is pending.'),
    s('Resolve', 'Re-render', 'Promise resolves — React re-renders the boundary with actual content.'),
  ]),
  'technical-debt': flow([
    s('Shortcut', 'Fast delivery', 'Team takes shortcut to ship fast — incurs technical debt.'),
    s('Debt grows', 'Slower over time', 'Each feature takes longer. Code harder to understand and change.'),
    s('Measure', 'Tech debt ratio', 'Quantify: static analysis estimates remediation cost vs. codebase size.'),
    s('Prioritise', 'Risk × impact', 'Prioritise by: How often is this code changed? What\'s the blast radius?'),
    s('Pay down', 'Refactor sprints', 'Allocate 20% of sprint capacity to debt reduction. Track trend.'),
  ]),
  'test-doubles': flow([
    s('Identify', 'Collaborator', 'Identify which collaborator to replace: DB, email, external API.'),
    s('Dummy', 'Never called', 'Dummy: passed but never used — satisfies parameter signature.'),
    s('Stub', 'Fixed return', 'Stub: returns preset value. Use when you need a specific response.'),
    s('Mock', 'Behaviour verify', 'Mock: records calls — assert it was called with correct args.'),
    s('Fake', 'Working impl', 'Fake: simplified working implementation, e.g. in-memory DB.'),
  ]),
  'testing-pyramid-frontend': flow([
    s('Unit tests', 'Many — fast', 'Unit tests: test single functions/hooks in isolation. Hundreds, milliseconds.'),
    s('Component', 'RTL render', 'Component tests: render in jsdom, interact, assert on DOM. Dozens.'),
    s('Integration', 'API + UI', 'Integration tests: frontend + mock API. Validate flows end-to-end.'),
    s('E2E', 'Few — slow', 'E2E (Playwright/Cypress): real browser, real server. Few, minutes.'),
    s('Balance', 'Pyramid shape', 'More units, fewer E2E. E2E are fragile and slow — use sparingly.'),
  ]),
  'this-binding': flow([
    s('Default', 'global / undefined', 'Default binding: standalone call → this = window (sloppy) or undefined (strict).'),
    s('Implicit', 'obj.method()', 'Implicit: method called on object → this = that object.'),
    s('Explicit', '.call/.apply/.bind', 'Explicit: call(ctx) / apply(ctx) / bind(ctx) set this manually.'),
    s('new binding', 'new Ctor()', 'new: creates fresh object, sets this to it, returns it.'),
    s('Arrow fn', 'Lexical this', 'Arrow function: no own this — inherits from surrounding lexical scope.'),
  ]),
  'threads-vs-processes': flow([
    s('Process', 'OS creates', 'Process: independent execution unit. Own memory space, file handles.'),
    s('Fork', 'Copy-on-write', 'fork() creates child process. Memory shared copy-on-write until mutation.'),
    s('Thread', 'Shared memory', 'Thread: lightweight execution unit within a process. Shares heap with siblings.'),
    s('Context switch', 'Threads cheaper', 'Thread context switch cheaper than process (no MMU flush).'),
    s('Hazards', 'Race conditions', 'Shared memory → race conditions. Use locks, atomics, message passing.'),
  ]),
  'transpilation-babel': flow([
    s('Source', 'ES2024 / JSX', 'Modern JS or JSX written by developer.'),
    s('Parse', 'AST created', 'Babel parses source into Abstract Syntax Tree.'),
    s('Transform', 'Plugin chain', 'Each Babel plugin traverses and transforms the AST.'),
    s('Generate', 'ES5 output', 'Babel generates ES5-compatible code from the transformed AST.'),
    s('Bundle', 'Webpack / Vite', 'Transpiled code bundled with other modules for the browser.'),
  ]),
  'tree-shaking': flow([
    s('ES modules', 'Static imports', 'Tree-shaking requires ES module static imports — no dynamic require().'),
    s('Entry point', 'Module graph', 'Bundler builds a module dependency graph from the entry point.'),
    s('Mark used', 'Live bindings', 'Bundler marks all exported bindings that are actually imported.'),
    s('Eliminate', 'Dead code', 'Unused exports removed — not included in the output bundle.'),
    s('sideEffects', 'package.json flag', '"sideEffects": false signals all modules are safe to tree-shake.'),
  ]),
  'trunk-based-development': flow([
    s('Commit', 'Direct to main', 'Developer commits small, complete change directly to main (trunk).'),
    s('CI', 'Runs immediately', 'CI triggered on every commit — build and tests must pass before merge.'),
    s('Feature flags', 'Incomplete work', 'Incomplete features hidden behind feature flags — merged but not active.'),
    s('Release', 'Any commit', 'Any green commit on main is potentially releasable.'),
    s('No long branches', 'Max 1 day', 'Feature branches last < 1 day. No long-lived branches to merge.'),
  ]),
  'unit-vs-integration-e2e': flow([
    s('Unit', 'Isolated function', 'Unit test: single function/class, all dependencies mocked. Fast, cheap.'),
    s('Integration', 'Multiple modules', 'Integration test: two or more real modules working together (e.g. service + DB).'),
    s('E2E', 'Full stack', 'E2E test: real browser + real server + real DB. Slow but highest confidence.'),
    s('Trade-offs', 'Speed vs coverage', 'Units fast but miss integration bugs. E2E catches most bugs but expensive.'),
    s('Pyramid', '70 / 20 / 10', 'Aim for ~70% unit, ~20% integration, ~10% E2E by test count.'),
  ]),
  'useeffect-internals': flow([
    s('Render', 'Component runs', 'Component function runs — effects NOT yet executed.'),
    s('Commit', 'DOM updated', 'React commits DOM changes. Browser paints.'),
    s('Effect runs', 'After paint', 'useEffect callback runs after paint — does not block browser.'),
    s('Deps check', 'Stale closure?', 'On re-render: React checks dependency array. Changed deps → cleanup + re-run.'),
    s('Cleanup', 'Return fn', 'Cleanup function (return () => ...) runs before re-run and on unmount.'),
  ]),
  'web-components': flow([
    s('Define', 'customElements.define', 'CustomElement class extends HTMLElement. Registered with customElements.define.'),
    s('Shadow DOM', 'attachShadow()', 'Shadow root attached — encapsulates DOM and CSS inside the element.'),
    s('Template', '<template>', '<template> element defines reusable HTML that is not rendered until cloned.'),
    s('Slots', '<slot>', '<slot> projects Light DOM children into Shadow DOM positions.'),
    s('Use', '<my-element>', 'Element used in any HTML — framework-agnostic. Lifecycle callbacks fire.'),
  ]),
  'worker-threads': flow([
    s('Main', 'Node.js event loop', 'Node main thread: event loop handles I/O, coordinates workers.'),
    s('Create', 'new Worker(file)', 'Worker thread spawned from a separate JS file.'),
    s('CPU work', 'Heavy computation', 'CPU-intensive task runs in worker — does not block event loop.'),
    s('Transfer', 'SharedArrayBuffer', 'Large data transferred via SharedArrayBuffer (zero-copy) or postMessage.'),
    s('Result', 'postMessage back', 'Worker posts result back. Main thread handles in onmessage callback.'),
  ]),
  'xss-cross-site-scripting': flow([
    s('Input', 'Malicious script', 'Attacker injects <script>alert(document.cookie)</script> into input.'),
    s('Stored', 'Persisted in DB', 'Stored XSS: injected script saved in DB and served to other users.'),
    s('Reflected', 'URL parameter', 'Reflected XSS: script injected via URL query string — phishing link.'),
    s('Executes', 'Victim\'s browser', 'Victim loads page — script runs in their browser context.'),
    s('Prevent', 'Encode + CSP', 'Fix: HTML-encode output, use CSP headers, avoid innerHTML with user data.'),
  ]),
  'color-contrast-wcag': flow([
    s('Foreground', 'Text colour', 'Measure foreground colour relative luminance (R,G,B formula).'),
    s('Background', 'BG colour', 'Measure background colour relative luminance.'),
    s('Ratio', '(L1+0.05)/(L2+0.05)', 'Calculate contrast ratio using WCAG formula.'),
    s('AA check', '4.5:1 normal', 'AA standard: 4.5:1 for normal text, 3:1 for large text (18pt+).'),
    s('AAA check', '7:1 enhanced', 'AAA enhanced: 7:1 for normal text. Higher bar for maximum accessibility.'),
  ]),
  'cqrs': flow([
    s('Command', 'Write intent', 'Command issued: CreateOrder — intent to change state, no return data.'),
    s('Command handler', 'Validate + execute', 'Handler validates command, applies business rules, updates write model.'),
    s('Event emitted', 'OrderCreated', 'Domain event published after state change.'),
    s('Query', 'Read request', 'Query issued: GetOrder — read-only, no side effects.'),
    s('Read model', 'Optimised view', 'Read model updated by event handler — optimised for query access patterns.'),
  ]),
};

let updated = 0;
const files = fs.readdirSync(dir).filter(f => f.endsWith('.json'));
files.forEach(f => {
  const fp = path.join(dir, f);
  const c = JSON.parse(fs.readFileSync(fp, 'utf8'));
  if (configs[c.slug]) {
    c.visualization.config = configs[c.slug];
    fs.writeFileSync(fp, JSON.stringify(c, null, 2));
    updated++;
  }
});
console.log('Timeline-step configs (batch A) applied to', updated, 'files.');
