import fs from 'fs';
import path from 'path';

const dir = 'src/data/concepts';

// Per-file complexity replacements: [tc, sc] — null means keep existing value
const fixes = {
  'acid-properties-01.json':              ['O(1) per transaction check', 'O(1) — metadata only'],
  'adapter-pattern-01.json':              [null, 'O(1) — wraps existing object'],
  'api-design-principles-01.json':        ['O(1) per request routing', 'O(1) — stateless design'],
  'api-gateway-01.json':                  ['O(1) routing overhead', 'O(N) active connections'],
  'api-pagination-01.json':               [null, 'O(1) cursor state'],
  'api-versioning-01.json':               ['O(1) per version lookup', 'O(V) version handlers'],
  'aria-roles-01.json':                   ['O(N) DOM traversal', 'O(N) accessibility tree'],
  'async-await-internals-01.json':        ['O(1) per microtask dispatch', null],
  'async-await-js-01.json':               ['O(1) per await', 'O(N) pending promises'],
  'bdd-basics-01.json':                   ['O(S) scenarios to run', 'O(S) scenario state'],
  'branch-strategies-01.json':            ['O(C) commits to merge', 'O(B) active branches'],
  'bundle-analysis-01.json':              ['O(N) modules at build time', 'O(N) bundle entries'],
  'bundlers-internals-01.json':           [null, 'O(N) module graph nodes'],
  'caching-strategies-frontend-01.json':  [null, 'O(N) cached entries'],
  'canary-releases-01.json':              ['O(1) per traffic split decision', 'O(I) instances'],
  'cap-theorem-01.json':                  ['O(1) per consistency check', 'O(N) replicas'],
  'cdn-basics-01.json':                   ['O(1) cache hit; O(N) on miss', 'O(N) cached assets'],
  'chaos-engineering-01.json':            ['O(E) experiments running', 'O(L) experiment logs'],
  'cherry-pick-01.json':                  ['O(D) diff size', 'O(D) patch size'],
  'cicd-pipelines-01.json':               [null, 'O(A) artifacts stored'],
  'circuit-breaker-01.json':              ['O(1) per request check', 'O(W) sliding window'],
  'clean-architecture-01.json':           ['O(1) per dependency rule check', 'O(L) layers'],
  'closures-js-01.json':                  ['O(1) per closure access', null],
  'code-coverage-01.json':                ['O(N) lines instrumented', 'O(N) coverage data'],
  'code-review-best-practices-01.json':   ['O(D) diff lines reviewed', 'O(C) comments stored'],
  'code-splitting-react-01.json':         ['O(C) chunks at load time', 'O(C) loaded chunks'],
  'code-splitting-strategies-01.json':    ['O(C) chunks at build time', 'O(C) code chunks'],
  'color-contrast-wcag-01.json':          ['O(1) ratio calculation', 'O(1) — single ratio value'],
  'command-pattern-01.json':              ['O(1) per command execute', null],
  'component-lifecycle-01.json':          ['O(R) re-renders triggered', 'O(E) effect closures'],
  'concurrent-mode-01.json':              ['O(U) units of work', 'O(F) fiber nodes'],
  'connection-pooling-01.json':           ['O(1) per connection acquire', 'O(P) pool connections'],
  'container-queries-01.json':            ['O(N) matched elements', 'O(N) style rules'],
  'context-api-01.json':                  ['O(C) consumers re-rendered', 'O(1) context value'],
  'contract-testing-01.json':             ['O(T) contract tests', 'O(C) contracts stored'],
  'core-web-vitals-01.json':              ['O(N) DOM events measured', 'O(N) metric samples'],
  'cors-01.json':                         ['O(1) per header check', 'O(H) allowed origins'],
  'cors-attacks-01.json':                 ['O(1) per origin validation', 'O(1) — policy state'],
  'cqrs-01.json':                         ['O(1) command dispatch; O(Q) query read', 'O(E) event history'],
  'critical-rendering-path-01.json':      ['O(N) DOM + CSSOM nodes', 'O(N) render tree nodes'],
  'csrf-01.json':                         ['O(1) per token validation', 'O(1) token per session'],
  'css-animations-01.json':               [null, 'O(A) active animations'],
  'css-custom-properties-01.json':        ['O(N) property cascade lookups', 'O(P) custom properties'],
  'css-grid-01.json':                     [null, 'O(N*M) grid cells'],
  'css-specificity-cascade-01.json':      ['O(N) rules to evaluate', 'O(N) style rules'],
  'database-migrations-01.json':          ['O(M) migration steps', 'O(M) migration history'],
  'database-normalization-01.json':       ['O(N) query joins needed', 'O(N) normalized rows'],
  'database-replication-01.json':         ['O(W) write propagation lag', 'O(R) replica count'],
  'database-scaling-patterns-01.json':    ['O(1) per routed query', 'O(N) distributed data'],
  'database-sharding-01.json':            ['O(1) shard lookup; O(N/S) per shard', 'O(N) distributed'],
  'database-transactions-01.json':        ['O(L) log entries written', 'O(L) transaction log'],
  'dead-letter-queues-01.json':           ['O(1) per message route', 'O(D) dead messages'],
  'decorator-pattern-01.json':            [null, 'O(D) decorator chain'],
  'dependency-injection-01.json':         ['O(G) dependency graph resolution', 'O(G) dependency graph'],
  'dependency-inversion-01.json':         ['O(1) per abstraction call', 'O(I) interface definitions'],
  'disaster-recovery-01.json':            ['O(D) dependent services restored', 'O(S) system state'],
  'dns-resolution-01.json':               ['O(H) resolver hops; O(1) cached', 'O(C) DNS cache entries'],
  'docker-internals-01.json':             ['O(L) layer lookups on start', null],
  'docker-networking-01.json':            ['O(1) per packet route', 'O(N) network namespaces'],
  'documentation-as-code-01.json':        ['O(N) docs pages built', 'O(N) doc artifacts'],
  'domain-driven-design-01.json':         ['O(1) per domain event', 'O(A) aggregate state'],
  'dry-kiss-yagni-01.json':               ['Reduces O(N) duplicated code', 'Reduces O(N) code size'],
  'environment-management-01.json':       ['O(E) environment configs', 'O(E*V) env variables'],
  'error-boundaries-01.json':             ['O(1) per error catch', 'O(1) error state'],
  'esm-vs-cjs-01.json':                   ['O(D) static deps at parse time', 'O(D) module graph'],
  'event-driven-architecture-01.json':    ['O(1) publish; O(S) fan-out', 'O(Q) queued events'],
  'event-loop-browser-01.json':           ['O(T) tasks in queue', 'O(T) task queue depth'],
  'event-loop-nodejs-01.json':            ['O(P) pending I/O operations', 'O(P) callback queue'],
  'event-sourcing-01.json':               ['O(E) events to replay', null],
  'eventual-consistency-01.json':         ['O(R) replica sync time', 'O(R) replica states'],
  'facade-pattern-01.json':               ['O(1) per facade call', 'O(1) — delegates to subsystem'],
  'factory-pattern-01.json':              [null, 'O(T) registered types'],
  'flexbox-algorithm-01.json':            [null, 'O(N) flex items'],
  'font-optimization-01.json':            ['O(G) glyph subsets loaded', 'O(F) font files cached'],
  'github-actions-01.json':               [null, 'O(A) artifact storage'],
  'graphql-basics-01.json':               ['O(R) resolver chain depth', 'O(R) resolver results'],
  'grpc-01.json':                         ['O(1) per RPC call (binary)', 'O(S) stream buffers'],
  'helm-basics-01.json':                  ['O(T) templates rendered', 'O(R) release history'],
  'hexagonal-architecture-01.json':       ['O(1) per port adapter call', 'O(P) port definitions'],
  'horizontal-vs-vertical-scaling-01.json': ['O(1) per node addition', null],
  'http-versions-01.json':                ['O(S) concurrent streams (HTTP/2)', 'O(H) header table (HPACK)'],
  'hydration-islands-01.json':            ['O(I) islands to hydrate', 'O(I) island state'],
  'idempotency-01.json':                  ['O(1) per idempotency key lookup', 'O(K) stored keys'],
  'image-optimization-01.json':           ['O(I) images processed at build', null],
  'incident-response-01.json':            ['O(S) systems to check', 'O(L) incident log entries'],
  'input-validation-01.json':             ['O(R) validation rules', 'O(1) per validation'],
  'interactive-rebase-01.json':           ['O(C) commits to rewrite', 'O(C) rewritten commits'],
  'job-queues-01.json':                   ['O(J) jobs processed per tick', null],
  'jwt-authentication-01.json':           ['O(1) stateless verification', 'O(1) — no server state'],
  'keyboard-navigation-01.json':          ['O(N) focusable elements', 'O(N) focus ring states'],
  'kubernetes-basics-01.json':            ['O(1) scheduling per pod', null],
  'kubernetes-services-deployments-01.json': ['O(P) pods managed', 'O(R) replica set history'],
  'lazy-loading-frontend-01.json':        ['O(V) visible items loaded', 'O(V) loaded items'],
  'lazy-vs-eager-loading-01.json':        ['O(1) lazy; O(N) eager upfront', null],
  'lighthouse-scoring-01.json':           ['O(A) audits run', 'O(A) audit results'],
  'load-balancing-01.json':               ['O(S) servers checked per request', 'O(S) server states'],
  'memory-leaks-backend-01.json':         ['O(1) detection per allocation', null],
  'memory-management-gc-01.json':         ['O(N) live objects traced', 'O(N) GC roots tracked'],
  'merge-vs-rebase-01.json':              ['O(C) commits processed', 'O(C) rewritten commits'],
  'message-delivery-guarantees-01.json':  ['O(1) per ack received', 'O(M) in-flight messages'],
  'microtasks-vs-macrotasks-01.json':     ['O(M) microtasks drained first', 'O(T) task queues'],
  'middleware-patterns-01.json':          ['O(M) middleware chain length', 'O(M) middleware stack'],
  'mocking-strategies-frontend-01.json':  [null, 'O(M) mock definitions'],
  'monorepo-vs-polyrepo-01.json':         ['O(P) packages to build', 'O(P) package caches'],
  'mutation-testing-01.json':             [null, 'O(M) mutant binaries'],
  'n-plus-one-query-01.json':             [null, 'O(N) extra queries fired'],
  'oauth2-01.json':                       ['O(1) token exchange', 'O(T) active tokens'],
  'observability-logs-metrics-traces-01.json': ['O(R) requests traced', null],
  'orm-patterns-01.json':                 ['O(Q) generated query complexity', 'O(M) model objects'],
  'overfitting-underfitting-01.json':     ['O(N*P) training examples x parameters', 'O(P) model parameters'],
  'owasp-top-10-01.json':                 ['O(1) per vulnerability check', 'O(C) security controls'],
  'password-hashing-01.json':             ['O(cost) — intentionally slow', 'O(1) hash output'],
  'postgresql-internals-01.json':         ['O(log N) B-tree index lookup', 'O(B) buffer pool pages'],
  'prefetching-preloading-01.json':       ['O(H) hints processed', 'O(R) prefetched resources'],
  'profiling-benchmarking-01.json':       ['O(N) samples collected', 'O(N) profile data'],
  'property-based-testing-01.json':       [null, 'O(N) test cases in memory'],
  'proxy-pattern-01.json':                [null, 'O(1) — wraps single subject'],
  'pubsub-pattern-01.json':               [null, 'O(S) subscriber list'],
  'pwa-basics-01.json':                   ['O(C) cached resources', 'O(C) cache storage'],
  'query-optimization-01.json':           ['O(log N) with index; O(N) without', 'O(1) index overhead'],
  'rabbitmq-01.json':                     ['O(1) publish; O(C) consumer fan-out', 'O(M) queued messages'],
  'rate-limiting-01.json':                ['O(1) per token bucket check', 'O(C) client counters'],
  'react-fiber-01.json':                  ['O(W) work units in fiber tree', 'O(F) fiber nodes'],
  'react-server-components-01.json':      ['O(C) server components rendered', 'O(S) serialized state'],
  'react-testing-library-01.json':        ['O(Q) queries run in test', 'O(D) DOM nodes'],
  'refactoring-patterns-01.json':         ['O(N) code sites to update', 'O(N) refactored units'],
  'reflow-vs-repaint-01.json':            [null, 'O(N) style recalculations'],
  'render-pipeline-01.json':              ['O(N) DOM + style recalcs', 'O(N) render pipeline stages'],
  'repository-pattern-01.json':           ['O(Q) query complexity', 'O(C) cached query results'],
  'request-animation-frame-01.json':      ['O(C) callbacks per frame (60fps)', 'O(C) rAF callbacks'],
  'responsive-design-01.json':            ['O(B) breakpoints evaluated', 'O(R) rule sets'],
  'rest-api-design-01.json':              ['O(1) per RESTful route lookup', 'O(R) route definitions'],
  'rest-principles-01.json':              ['O(1) stateless per request', 'O(1) — no server session'],
  'retry-and-backoff-01.json':            ['O(R) retry attempts', 'O(1) backoff state'],
  'reverse-proxy-01.json':                [null, 'O(C) concurrent connections'],
  'saga-pattern-01.json':                 ['O(S) saga steps', 'O(S) saga state'],
  'screen-reader-compatibility-01.json':  ['O(N) ARIA nodes traversed', 'O(N) accessibility tree'],
  'secrets-management-01.json':           ['O(1) per secret lookup', 'O(S) secrets stored'],
  'semantic-versioning-01.json':          ['O(1) per version parse', 'O(1) version string'],
  'server-sent-events-01.json':           ['O(1) per event push', 'O(C) open connections'],
  'service-workers-01.json':              ['O(C) cache strategy lookups', 'O(C) cached responses'],
  'session-authentication-01.json':       ['O(1) session lookup', null],
  'shadow-dom-01.json':                   ['O(N) shadow tree nodes', 'O(N) encapsulated styles'],
  'sla-design-01.json':                   ['O(D) dependent SLA checks', 'O(S) SLA definitions'],
  'snapshot-testing-01.json':             [null, 'O(S) snapshot files'],
  'solid-principles-01.json':             ['O(1) per dependency rule', 'O(A) abstractions defined'],
  'source-maps-01.json':                  ['O(N) at build generation', 'O(M) mapping table'],
  'sql-injection-01.json':                ['O(1) per parameterized query', 'O(1) — no extra state'],
  'ssl-termination-01.json':              [null, 'O(S) active TLS sessions'],
  'stacking-context-01.json':             ['O(N) stacking contexts', 'O(N) z-index layers'],
  'stateless-services-01.json':           ['O(1) per request (no session load)', 'O(1) — no instance state'],
  'static-analysis-01.json':              [null, 'O(N) AST nodes'],
  'strategy-pattern-01.json':             [null, 'O(S) strategies registered'],
  'suspense-react-01.json':               ['O(B) boundary checks', 'O(P) pending promises'],
  'system-design-api-gateway-01.json':    [null, 'O(R) routing rules'],
  'system-design-video-streaming-01.json': ['O(C) concurrent streams', null],
  'tcp-vs-udp-01.json':                   ['O(1) per TCP handshake', 'O(W) TCP window buffers'],
  'tdd-cycle-01.json':                    ['O(T) tests to run per cycle', 'O(T) test suite size'],
  'technical-debt-01.json':               ['O(D) debt items to remediate', 'O(D) tracked debt items'],
  'test-doubles-01.json':                 [null, 'O(D) test double definitions'],
  'testing-pyramid-frontend-01.json':     ['O(U+I+E) test suite size', 'O(T) test artifacts'],
  'this-binding-01.json':                 ['O(1) per binding lookup', 'O(1) — execution context'],
  'threads-vs-processes-01.json':         ['O(T) thread context switches', null],
  'tls-ssl-handshake-01.json':            ['O(R) handshake round trips', 'O(K) key material'],
  'transpilation-babel-01.json':          [null, 'O(N) transformed AST nodes'],
  'tree-shaking-01.json':                 [null, 'O(N) dependency graph nodes'],
  'trunk-based-development-01.json':      [null, 'O(1) — single integration branch'],
  'unit-vs-integration-e2e-01.json':      ['O(U) unit < O(I) integration < O(E) E2E', 'O(T) test fixtures'],
  'useeffect-internals-01.json':          ['O(D) dependency array size', 'O(E) active effects'],
  'web-components-01.json':               ['O(N) custom elements defined', 'O(N) shadow roots'],
  'web-workers-01.json':                  ['O(M) messages serialized', null],
  'webhooks-01.json':                     ['O(1) per event delivery', 'O(H) webhook handlers'],
  'websockets-01.json':                   ['O(1) per frame sent', 'O(C) open connections'],
  'xss-cross-site-scripting-01.json':     ['O(I) input fields sanitized', 'O(1) sanitization overhead'],
};

let updated = 0;
for (const [filename, [tc, sc]] of Object.entries(fixes)) {
  const fp = path.join(dir, filename);
  if (!fs.existsSync(fp)) { console.log('MISSING:', filename); continue; }
  const c = JSON.parse(fs.readFileSync(fp, 'utf8'));
  let changed = false;
  if (tc !== null && c.card.time_complexity === 'N/A') { c.card.time_complexity = tc; changed = true; }
  if (sc !== null && c.card.space_complexity === 'N/A') { c.card.space_complexity = sc; changed = true; }
  if (changed) { fs.writeFileSync(fp, JSON.stringify(c, null, 2)); updated++; }
}
console.log('Updated complexity in', updated, 'files');

// Verify none remain
const dir2 = dir;
const files = fs.readdirSync(dir2).filter(f => f.endsWith('.json'));
let remaining = 0;
files.forEach(f => {
  const c = JSON.parse(fs.readFileSync(path.join(dir2, f), 'utf8'));
  if (c.card?.time_complexity === 'N/A' || c.card?.space_complexity === 'N/A') {
    console.log('STILL N/A:', f, c.card.time_complexity, c.card.space_complexity);
    remaining++;
  }
});
console.log('Remaining N/A files:', remaining);
